#pragma once

#include <string>

#define _400 "<div style=\"text-align: center;\">    <p id=\"400\">        400 无法解析请求    </p></div></body></html>"
#define _403 "<div style=\"text-align: center;\">    <p id=\"403\">        403 禁止访问    </p></div></body></html>"
#define _404 "<div style=\"text-align: center;\">    <p id=\"404\">        404 没有找到该页面    </p></div></body></html>"
#define _head "<body>    <style>      </style>            <div class=\"header\">        <div class=\"Title\">          <ul>            <li><a class=\"navigation\" href=\"/\">首页</a></li>            <li><a class=\"navigation\" href=\"/public\">公共空间</a></li>            <li><a class=\"navigation\" href=\"/private\">个人空间</a></li>          </ul>        </div>              <div class=\"User\">          <ul>            <li><a class=\"navigation\" href=\"/login\">登录</a></li>            <li><a class=\"navigation\" href=\"/register\">注册</a></li>          </ul>        </div>      </div>"
#define _head_ "<body>    <style>      </style>            <div class=\"header\">        <div class=\"Title\">          <ul>            <li><a class=\"navigation\" href=\"/\">首页</a></li>            <li><a class=\"navigation\" href=\"/public\">公共空间</a></li>            <li><a class=\"navigation\" href=\"/private\">个人空间</a></li>          </ul>        </div>"
#define _index "<div style=\"text-align: center;\">    <p id=\"welcome\">        欢迎来到个人文件管理系统    </p></div></body></html>"
#define _login "    <div style=\"text-align: center\">        <h1>登录</h1>        <form action=\"login\" method=\"post\">            <div style=\"text-align: center\">                <input type=\"text\" name=\"username\" placeholder=\"用户名\" required=\"required\">            </div> <br/>            <div style=\"text-align: center\">                <input type=\"password\" name=\"password\" placeholder=\"用户密码\" required=\"required\">            </div> <br/>            <div style=\"text-align: center\"><button type=\"submit\">确认</button></div>        </form>    </div></body></html>"
#define _namerr "<div style=\"text-align: center;\">    <p id=\"welcome\">        用户名错误!    </p></div></body></html>"
#define _pwderr "<div style=\"text-align: center;\">    <p id=\"welcome\">        密码错误!    </p></div></body></html>"
#define _private "<div style=\"text-align: center\">    <br>        私人空间    <br/></div><div style=\"text-align: center\">    <br>    <div style=\"width:300px; text-align: left; margin: auto;\">选择文件上传：</div>    <br/>    <form id=\"uploadfile\" action=\"\"  method=\"post\" enctype=\"multipart/form-data\" style=\"text-align: center;\">            <input type=\"file\" id=\"upload\" name=\"upload\" style = \"border:1px solid;\" />            <input type=\"submit\" onclick=\"uploadWin()\" value=\"上传\" />    </form></div><div style=\"text-align: center\">    <br>        <div style=\"width:300px; text-align: left; margin: auto;\">文件列表：</div>    <br/>    <table border=\"1px\" style=\"width:600px;text-align: center; margin: auto;table-layout:fixed;\">        <thead>            <td style=\"text-align: center;\">文件名</td> <td></td> <td></td>        </thead>"
#define _public "<div style=\"text-align: center\">    <br>        公共空间    <br/></div><div style=\"text-align: center\">    <br>    <div style=\"width:300px; text-align: left; margin: auto;\">选择文件上传：</div>    <br/>    <form id=\"uploadfile\" action=\"\"  method=\"post\" enctype=\"multipart/form-data\" style=\"text-align: center;\">            <input type=\"file\" id=\"upload\" name=\"upload\" style = \"border:1px solid;\" />            <input type=\"submit\" onclick=\"uploadWin()\" value=\"上传\" />    </form></div><div style=\"text-align: center\">    <br>        <div style=\"width:300px; text-align: left; margin: auto;\">文件列表：</div>    <br/>    <table border=\"1px\" style=\"width:600px;text-align: center; margin: auto;table-layout:fixed;\">        <thead>            <td style=\"text-align: center;\">文件名</td> <td></td> <td></td>        </thead>"
#define _register "    <div style=\"text-align: center\">        <h1>注册</h1>        <form action=\"register\" method=\"post\">            <div style=\"text-align: center\">                <input type=\"text\" name=\"username\" placeholder=\"用户名\" required=\"required\">            </div> <br/>            <div style=\"text-align: center\">                <input type=\"password\" name=\"password\" placeholder=\"用户密码\" required=\"required\">            </div> <br/>            <div style=\"text-align: center\"><button type=\"submit\">确认</button></div>        </form>    </div></body></html>"
#define _title "<!DOCTYPE html><html lang=\"en\"><head>    <meta charset=\"UTF-8\">    <title>个人文件管理系统</title>    <style>        .header{            margin-right: 12px;            display: flex;            justify-content: space-between;        }        .header li{            list-style: none;            display: inline;            padding: 12px;            font-size: 25px;        }        .header a{            text-decoration: none;            color: black;        }        .Title{            text-align: left;        }        .User{            text-align: right;        }                #welcome{            font-size: 30px;        }        .navigation {          text-decoration: none;          color: #000;          padding: 5px 10px;        }                .load{            text-decoration: none;            color: black;            font-size: 20px;        }    </style>    <meta charset=\"UTF-8\"></head>"
#define _welcome "<div style=\"text-align: center;\">    <p id=\"welcome\">        登录成功!    </p></div></body></html>"
#define _listend "</table></div><script type=\"text/javascript\">    function confirmDelete() {        return confirm('确认删除该文件吗？');    }    function uploadWin(){        var vDiv = document.getElementById('div1');        vDiv.style.display = 'block';        vDiv.style.zIndex = 10;        vDiv.style.position = \"absolute\";        var vDiv2 = document.getElementById('div2');        vDiv2.style.display = 'block';        vDiv2.style.zIndex = 11;        vDiv2.style.position = \"fixed\";        vDiv2.style.top = \"20%\";        vDiv2.style.left = \"50%\";        vDiv2.style.marginLeft = \"-111px\";        vDiv2.style.marginTop = \"-20px\";    }</script></body></html>"
