#pragma once

#define STORAGE_STATUS_INIT 0
#define STORAGE_STATUS_WAIT_SYNC 1
#define STORAGE_STATUS_SYNC_RCVD 2
#define STORAGE_STATUS_SUNC_SEND 3
#define STORAGE_STATUS_ACTIVE 4


#define STORAGE_PACK_NEW 0
#define STORAGE_PACK_SYN 1
#define STORAGE_PACK_KEP 2
#define STORAGE_PACK_DEL 3